#!/usr/bin/env bash
# setup-app.sh — provision ONE independent BennyBlax application on this VPS.
#
# Each application gets its own:
#   - deploy config      deploy/apps/<app-id>.env            (non-secret)
#   - app directory      <APP_PATH>                          (source/build)
#   - Nginx virtual host /etc/nginx/sites-available/<app-id>.conf
#   - PostgreSQL DB      <DB_NAME> owned by dedicated user   <DB_USER>
#   - runtime secrets    <APP_PATH>/server/.env.production   (generated)
#   - log directory      /var/log/bennyblax/<app-id>
#
# Running this for a second application (e.g. motorcycle) is independent:
# it never modifies an existing application's files, database, process or
# Nginx virtual host.
#
# Usage:
#   deploy/setup-app.sh <app-id> [--render-only] [options...]
#
# Options:
#   --render-only      Only render deploy/rendered/<app-id>.conf from the
#                      template; make NO changes to the system. Safe for
#                      testing and CI.
#   --hostname H       APP_HOSTNAME override
#   --port P           API_PORT override (default 4100)
#   --db-name D        DB_NAME override
#   --db-user U        DB_USER override
#   --app-name N       APP_NAME (PM2 process name) override
#   --app-path P       APP_PATH override
#
# Environment overrides: PG_PSQL_CMD (default "sudo -u postgres psql"),
#   DB_PASSWORD (if not set, a strong random one is generated).

set -euo pipefail

APP_ID="${1:-}"
if [ -z "$APP_ID" ]; then
  echo "Usage: $0 <app-id> [--render-only] [--hostname H] [--port P] [--db-name D] [--db-user U] [--app-name N] [--app-path P]"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/deploy"
APPS_DIR="$DEPLOY_DIR/apps"
RENDER_DIR="$DEPLOY_DIR/rendered"
RENDER_ONLY=0

# --- Parse options -------------------------------------------------------
CLI_HOSTNAME=""
CLI_PORT=""
CLI_DB_NAME=""
CLI_DB_USER=""
CLI_APP_NAME=""
CLI_APP_PATH=""

i=2
while [ "$i" -le "$#" ]; do
  arg="${!i}"
  case "$arg" in
    --render-only) RENDER_ONLY=1 ;;
    --hostname)    i=$((i+1)); CLI_HOSTNAME="${!i}" ;;
    --port)        i=$((i+1)); CLI_PORT="${!i}" ;;
    --db-name)     i=$((i+1)); CLI_DB_NAME="${!i}" ;;
    --db-user)     i=$((i+1)); CLI_DB_USER="${!i}" ;;
    --app-name)    i=$((i+1)); CLI_APP_NAME="${!i}" ;;
    --app-path)    i=$((i+1)); CLI_APP_PATH="${!i}" ;;
    *)
      echo "Unknown option: $arg"
      exit 1
      ;;
  esac
  i=$((i+1))
done

# --- Load or create the app's deploy config ------------------------------
CONFIG_FILE="$APPS_DIR/$APP_ID.env"

if [ ! -f "$CONFIG_FILE" ]; then
  EXAMPLE="$APPS_DIR/$APP_ID.env.example"
  if [ -f "$EXAMPLE" ]; then
    cp "$EXAMPLE" "$CONFIG_FILE"
    echo "[setup] Created $CONFIG_FILE from example."
  else
    cat > "$CONFIG_FILE" <<EOF
# Generated by setup-app.sh — edit values for this application.
APP_ID=$APP_ID
APP_NAME=${CLI_APP_NAME:-bennyblax-${APP_ID}-api}
APP_HOSTNAME=${CLI_HOSTNAME:-${APP_ID}.yourdomain.com}
APP_PATH=${CLI_APP_PATH:-/opt/bennyblax/apps/${APP_ID}}
API_PORT=${CLI_PORT:-4100}
DB_NAME=${CLI_DB_NAME:-bennyblax_${APP_ID}}
DB_USER=${CLI_DB_USER:-bennyblax_${APP_ID}}
EOF
    echo "[setup] Created starter $CONFIG_FILE."
  fi
fi

# shellcheck disable=SC1090
. "$CONFIG_FILE"

# Apply CLI overrides on top of the config file values.
APP_HOSTNAME="${CLI_HOSTNAME:-$APP_HOSTNAME}"
API_PORT="${CLI_PORT:-$API_PORT}"
DB_NAME="${CLI_DB_NAME:-$DB_NAME}"
DB_USER="${CLI_DB_USER:-$DB_USER}"
APP_NAME="${CLI_APP_NAME:-$APP_NAME}"
APP_PATH="${CLI_APP_PATH:-$APP_PATH}"

APP_HOSTNAME="${APP_HOSTNAME:-${APP_ID}.yourdomain.com}"
API_PORT="${API_PORT:-4100}"
DB_NAME="${DB_NAME:-bennyblax_${APP_ID}}"
DB_USER="${DB_USER:-bennyblax_${APP_ID}}"
APP_NAME="${APP_NAME:-bennyblax-${APP_ID}-api}"
APP_PATH="${APP_PATH:-/opt/bennyblax/apps/${APP_ID}}"

APP_LOG_DIR="/var/log/bennyblax/${APP_ID}"

echo "[setup] Config for '$APP_ID': hostname=$APP_HOSTNAME port=$API_PORT db=$DB_NAME path=$APP_PATH"

# --- Render the Nginx virtual host ---------------------------------------
if ! command -v envsubst >/dev/null 2>&1; then
  echo "[setup] ERROR: envsubst not found. Install gettext (e.g. apt install gettext)."
  exit 1
fi

mkdir -p "$RENDER_DIR"
RENDERED="$RENDER_DIR/$APP_ID.conf"
export APP_HOSTNAME APP_PATH API_PORT APP_LOG_DIR
envsubst '$APP_HOSTNAME $APP_PATH $API_PORT $APP_LOG_DIR' \
  < "$DEPLOY_DIR/templates/nginx-site.conf" > "$RENDERED"
echo "[setup] Rendered Nginx virtual host: $RENDERED"

if [ "$RENDER_ONLY" = "1" ]; then
  echo "[setup] --render-only set; no system changes performed."
  exit 0
fi

# --- Create application directories --------------------------------------
mkdir -p "$APP_PATH" "/opt/bennyblax/backups/$APP_ID" "$APP_LOG_DIR"
echo "[setup] Created directories: $APP_PATH, /opt/bennyblax/backups/$APP_ID, $APP_LOG_DIR"

# --- Install Nginx virtual host ------------------------------------------
if [ -d /etc/nginx/sites-available ]; then
  cp "$RENDERED" "/etc/nginx/sites-available/$APP_ID.conf"
  ln -sfn "/etc/nginx/sites-available/$APP_ID.conf" "/etc/nginx/sites-enabled/$APP_ID.conf"
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx >/dev/null 2>&1 || service nginx reload >/dev/null 2>&1 || true
    echo "[setup] Installed and reloaded Nginx virtual host: $APP_ID.conf"
  else
    echo "[setup] WARNING: nginx -t failed — fix before reloading."
    nginx -t
  fi
else
  echo "[setup] WARNING: /etc/nginx/sites-available not found — install Nginx or copy $RENDERED manually."
fi

# --- Create the dedicated PostgreSQL database and user -------------------
if command -v psql >/dev/null 2>&1; then
  PG_PSQL_CMD="${PG_PSQL_CMD:-sudo -u postgres psql}"
  DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 24)}"

  $PG_PSQL_CMD -v ON_ERROR_STOP=1 >/dev/null <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD';
  ELSE
    ALTER ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD';
  END IF;
END
\$\$;
SQL

  if ! $PG_PSQL_CMD -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
    sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
    echo "[setup] Created database: $DB_NAME (owner: $DB_USER)"
  else
    echo "[setup] Database $DB_NAME already exists."
  fi
  echo "[setup] Database user $DB_USER password regenerated and stored in the app env file."
else
  echo "[setup] WARNING: psql not found — create the database manually (see docs/MULTIAPP.md)."
  DB_PASSWORD="__set_me__"
fi

# --- Scaffold the application runtime env (secrets) ----------------------
ENV_FILE="$APP_PATH/server/.env.production"
if [ -f "$ENV_FILE" ]; then
  echo "[setup] $ENV_FILE already exists — leaving it untouched."
else
  mkdir -p "$APP_PATH/server"
  JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 64)}"
  cat > "$ENV_FILE" <<EOF
# Production environment for $APP_NAME — generated by setup-app.sh.
# Fill in SMTP_* values. Never commit this file.
NODE_ENV=production
PORT=$API_PORT
CLIENT_ORIGIN=https://$APP_HOSTNAME
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=8h
EMAIL_PROVIDER=smtp
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=no-reply@$APP_HOSTNAME
EOF
  chmod 600 "$ENV_FILE"
  echo "[setup] Generated $ENV_FILE (JWT + DB credentials). Fill in SMTP_* and build."
fi

echo
echo "[setup] Next steps for '$APP_ID':"
echo "  1. cd $APP_PATH"
echo "  2. Copy your source into $APP_PATH (or deploy the repo there)."
echo "  3. server: npm ci --omit=dev && npx prisma generate && npx prisma migrate deploy && npm run build"
echo "  4. client: cd client && npm ci && npm run build   (leave VITE_API_URL empty = same-origin)"
echo "  5. provision admin: cd server && ADMIN_EMAIL=you@example.com npx tsx scripts/provision-admin.ts"
echo "  6. pm2 start $DEPLOY_DIR/ecosystem.config.cjs && pm2 save && pm2 startup"
echo "  7. TLS: sudo certbot certonly --webroot -w /var/www/certbot -d $APP_HOSTNAME"
echo "[setup] Done ($APP_ID)."